version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
      - MYSQL_DATABASE=eventsProject
      - innodb_force_recovery=1
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  tp-foyer-app:
    depends_on:
      - mysqldb
    image: ghassenjebari/eventsproject-1.0.0
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: |
        {
          "spring.datasource.url": "jdbc:mysql://mysqldb:3306/eventsProject?createDatabaseIfNotExist=true",
          "spring.datasource.username": "root",
          "server.port": "8082",
          "spring.datasource.password": "rootpassword",
          "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQLDialect",
          "spring.jpa.hibernate.ddl-auto": "update"
        }
    stdin_open: true
    tty: true

volumes:
  db:
